In [1]:
import numpy as np

In [2]:
# recall
np.zeros(4, dtype=int)

array([0, 0, 0, 0])

In [3]:
# using a compound dtype specification
data = np.zeros(4, dtype={
                            'names':('name','age','weight'),
                            'formats':('U10','i4','f8')
                         })
data

array([('', 0, 0.), ('', 0, 0.), ('', 0, 0.), ('', 0, 0.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [10]:
# fill it up
data['name']='Snyder'
data['age']=25
data['weight']=80
print(data)

[('Snyder', 25, 80.) ('Snyder', 25, 80.) ('Snyder', 25, 80.)
 ('Snyder', 25, 80.)]


In [11]:
# get all names
data['name']

array(['Snyder', 'Snyder', 'Snyder', 'Snyder'], dtype='<U10')

In [12]:
# first row
data[0]

('Snyder', 25, 80.)

In [16]:
data[1] = ('Pruddy',20,78)
data[2] = ('Everlyne',50,90 )
data[3] = ('Borough',31,89)

In [17]:
# name from the last row
data[-1]['name']

'Borough'

In [18]:
# filtering age < 50
data['age'] < 50

array([ True,  True, False,  True])

In [25]:
# get names of people age<50
data[data['age']<50]['name']

array(['Snyder', 'Pruddy', 'Borough'], dtype='<U10')

In [ ]:
""" Creating structured array """

In [27]:
# coumpoud dtype
np.dtype([('name','S10'), ('age','i4'),('weight','f8')])

dtype([('name', 'S10'), ('age', '<i4'), ('weight', '<f8')])

In [39]:
""" Advanced Compound Types """

tp = np.dtype([('id','i8'),('mat','f8',(3,3))])
x = np.zeros(1, dtype=tp)
print(x[0])
print(x['mat'][0])
print(x['id'])

(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[0]


In [40]:
""" Record Arrays"""
# prev
data['age']

array([25, 20, 50, 31])

In [41]:
# with recarray
data_r = data.view(np.recarray)
data_r.age

array([25, 20, 50, 31])

In [ ]:
# it's however slower